apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: k8spspseccompannotation
spec:
  match:
    scope: Namespaced
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
  location: metadata.annotations."seccomp.security.alpha.kubernetes.io/pod"
  parameters:
    assign:
      value: runtime/default
